name: build and deploy

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_REPOSITORY: tdeheurles/interview09052023
  GKE_PROJECT: interview09052023
  GKE_ZONE: europe-west9-a
  GKE_CLUSTER: my-gke-cluster
  KUBECONFIG: kubeconfig.yaml

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./web
        push: true
        tags: ${{ env.DOCKERHUB_REPOSITORY }}:0.1.${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ env.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }} --project ${{ env.GKE_PROJECT }} --internal-ip --quiet
        kubectl config use-context ${{ env.GKE_CLUSTER }}
        kubectl config view --flatten --minify > ${{ env.KUBECONFIG }}


    - name: Deploy to GKE
      run: |
        export KUBECONFIG=${{ env.KUBECONFIG }}
        export DOCKERHUB_REPOSITORY=${{ env.DOCKERHUB_REPOSITORY }}
        export DOCKERHUB_TAG=${{ github.run_number }}
        envsubst < k8s/kustomization.tmpl.yaml > k8s/kustomization.yaml
        kubectl kustomize k8s | kubectl apply -f -
